name: BFI Scraper

on:
  workflow_dispatch:
  schedule:
    - cron: "0 */6 * * *"   # 6 saatte bir (istersen değiştir)

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - name: Reponun klonlanması
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Node kurulumu
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Puppeteer için bağımlılıkların kurulması
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libnss3 \
            libatk1.0-0 \
            libcups2 \
            libxss1 \
            libasound2t64 \
            libatk-bridge2.0-0 \
            libgtk-3-0 \
            libx11-xcb1 \
            libxcb-dri3-0 \
            libdrm2 \
            libgbm1 \
            libxdamage1 \
            libxcomposite1 \
            libxrandr2 \
            libxkbcommon0 \
            libpango-1.0-0 \
            libcairo2

      - name: NPM install
        run: npm install

      - name: Scraper çalıştırılıyor
        run: node scripts/scraper.js

      - name: Commit changes (countries.json + debug.html)
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add data/countries.json
          git add data/debug.html
          git commit -m "Auto update scraped data" || echo "No changes"
          git push
